# Generated by Django 5.1.1 on 2024-09-16 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_foodentry_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
